[package]
name = "sino"
version = "0.1.0"
authors = ["Piripant <piripant@gmail.com>"]

[dependencies]
piston_window = "0.80.0"
image = "0.19.0"
rand = "0.5.5"
pingui = { git = "https://github.com/Piripant/pingui" }